---
services:
      
  sonarqube:
    image: sonarqube:latest
    container_name: server-sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=${POSTGRES_SONAR_USER:-sonarqube}
      - SONARQUBE_JDBC_PASSWORD=${POSTGRES_SONAR_PASSWORD:-sonarqube}
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres-sonarqube:5435/sonar
    depends_on:
      - postgres-sonarqube
    restart: unless-stopped
    networks:
      devsecopstoolnet:
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.13
    container_name: server-artifactory
    ports:
      - "9001:8081"
    restart: always
    depends_on:
      - postgres-artifactory
    links:
      - postgres-artifactory
    networks:
      devsecopstoolnet:
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory
    environment:
      - DB_TYPE=postgresql
     # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
      - DB_USER=${POSTGRES_ARTIFACTORY_USER:-artifactory}
      - DB_PASSWORD=${POSTGRES_ARTIFACTORY_PASSWORD:-artifactory}
      - DB_PORT=${POSTGRES_ARTIFACTORY_PORT:-5036}
     # Add extra Java options by uncommenting the following line
     #- EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  
  gitea:
    image: gitea/gitea:latest
    container_name: server-gitea
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres-gittea:${POSTGRES_GITTEA_PORT:-5037}
      - DB_NAME=${POSTGRES_GITTEA_DB:-gittea}
      - DB_USER=${POSTGRES_GITTEA_USER:-gittea}
      - DB_PASSWD=${POSTGRES_GITTEA_PASSWORD:-gittea}
    depends_on:
      - postgres-gittea
    restart: always
    networks:
      devsecopstoolnet:
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro  
      
  nexus:
    image: sonatype/nexus3:latest
    container_name: server-nexus
    ports:
      - "9003:8081"
      - "8085:8085"
    restart: always
    networks:
      devsecopstoolnet:
    volumes:
      - "nexus-data:/sonatype-work"
       
  postgres-sonarqube:
    image: postgres:latest
    container_name: postgres-sonarqube
    restart: unless-stopped
    networks:
      devsecopstoolnet:
    ports: 
      - "5435:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_SONAR_USER:-sonarqube}
      - POSTGRES_PASSWORD=${POSTGRES_SONAR_PASSWORD:-sonarqube}
    volumes:
      - postgresql-sonarqube-data:/var/lib/postgresql
      
  postgres-artifactory:
    image: postgres:latest
    container_name: postgres-artifactory
    restart: unless-stopped
    networks:
      devsecopstoolnet:
    ports: 
      - "5436:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_ARTIFACTORY_USER:-artifactory}
      - POSTGRES_PASSWORD=${POSTGRES_ARTIFACTORY_PASSWORD:-artifactory}
    volumes:
      - postgresql-artifactory-data:/var/lib/postgresql

  postgres-gittea:
    image: postgres:latest
    container_name: postgres-gittea
    restart: unless-stopped
    networks:
      devsecopstoolnet:
    ports: 
      - "5437:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_GITTEA_USER:-gittea}
      - POSTGRES_PASSWORD=${POSTGRES_GITTEA_PASSWORD:-gittea}
      - POSTGRES_DB=${POSTGRES_GITTEA_DB:-gittea}
    volumes:
      - postgresql-gittea-data:/var/lib/postgresql
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-palutla@yahoo.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - devsecopstoolnet
    restart: unless-stopped
    
networks:
  devsecopstoolnet:
    external: false
    
volumes:
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
  artifactory-data:
    driver: local 
  nexus-data: 
    driver: local
  gitea-data:
    driver: local
  postgresql-sonarqube-data:
    driver: local
  postgresql-artifactory-data:
    driver: local
  postgresql-gittea-data:
    driver: local
  pgadmin-data:
    driver: local
  
